version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/react_app/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
    - location: scripts/create_test_db.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
